services:
  activemq:
    image: apache/activemq-classic:6.1.7
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    networks:
      - gym-network
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/61616' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gym-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Discovery
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - gym-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Microservices
  training-service:
    build:
      context: ./training
      dockerfile: Dockerfile
    container_name: training-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      eureka-server:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - gym-network
    restart: on-failure

  workload-service:
    build:
      context: ./workload
      dockerfile: Dockerfile
    container_name: workload-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      eureka-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      activemq:
        condition: service_healthy
    networks:
      - gym-network
    restart: on-failure

networks:
  gym-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  mongodb_data:
    driver: local