server:
  port: 8081

spring:
  application:
    name: workload-service

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: workloaddb

  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    packages:
      trust-all: true

queues:
  training: training.queue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: workload-service